# Generated by Django 5.0.7 on 2026-02-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
