# Generated by Django 5.0.7 on 2026-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='subtitle',
        ),
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File (name|url)'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('realesed', 'Realesed'), ('archive', 'Archive')], default='realesed', max_length=20),
        ),
    ]
