# Generated by Django 5.0.7 on 2026-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_type_project_subtitle_project_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('pet', 'Pet Project'), ('open_source', 'Open Source'), ('startup', 'Start Up')], default='pet', max_length=100),
        ),
    ]
