# Generated by Django 5.0.7 on 2026-02-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0020_primarybio_url_resume'),
        ('projects', '0011_project_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='primary_skill',
        ),
        migrations.AddField(
            model_name='project',
            name='primary_skills',
            field=models.ManyToManyField(related_name='primary_skills', to='biography.skill'),
        ),
    ]
